"""
PDF Report Generator
====================
Generates investor-grade PDF technical analysis reports using ReportLab + Matplotlib.

Entry point:
    generate_pdf_report(analysis_response, dataframes_by_ticker) -> bytes

Charts are rendered by matplotlib into BytesIO and embedded into the PDF.
No disk writes required.
"""

import io
from datetime import datetime
from typing import Dict, List, Optional

import numpy as np
import pandas as pd
from scipy.signal import find_peaks

import matplotlib
matplotlib.use("Agg")  # non-interactive server backend
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.ticker as mticker
from matplotlib.patches import FancyArrowPatch
from matplotlib.lines import Line2D

plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "axes.unicode_minus": False,
    "figure.autolayout": False,
})

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, PageBreak, HRFlowable, KeepTogether,
)
from reportlab.pdfbase import pdfmetrics

from models.schemas import AnalysisResponse, TickerAnalysis
from models.enums import RiskLevel, TradeSignal, TrendDirection

# ─── Layout ───────────────────────────────────────────────────────────────────

PAGE_W, PAGE_H = A4
MARGIN        = 0.70 * inch
CONTENT_W     = PAGE_W - 2 * MARGIN
CHART_MAIN    = 3.3 * inch    # price / volume chart height
CHART_IND     = 2.0 * inch    # RSI / MACD / ATR
CHART_PATTERN = 3.8 * inch    # pattern overlay
CHART_SUMMARY = 2.6 * inch    # executive summary charts
DPI           = 130

TEMPLATE_VERSION = "1.0.0"

DISCLAIMER = (
    "DISCLAIMER: This report is generated by the Stock Pattern Engine for educational and "
    "informational purposes only. It does not constitute financial advice, investment advice, "
    "or a recommendation to buy or sell any security. Chart patterns are probabilistic tools "
    "and do not guarantee future results. Past performance is not indicative of future "
    "performance. Always conduct your own research and consult a qualified financial adviser "
    "before making any investment decisions."
)

# ─── Colour Palette (ReportLab) ───────────────────────────────────────────────

C_NAVY    = colors.HexColor("#1e3a5f")
C_BLUE    = colors.HexColor("#2563eb")
C_SLATE   = colors.HexColor("#475569")
C_MUTED   = colors.HexColor("#94a3b8")
C_LIGHT   = colors.HexColor("#f1f5f9")
C_MED     = colors.HexColor("#e2e8f0")
C_GREEN   = colors.HexColor("#15803d")
C_LGREEN  = colors.HexColor("#dcfce7")
C_RED     = colors.HexColor("#b91c1c")
C_LRED    = colors.HexColor("#fee2e2")
C_AMBER   = colors.HexColor("#b45309")
C_LAMBER  = colors.HexColor("#fef3c7")
C_WHITE   = colors.white
C_BLACK   = colors.black

# Matplotlib palette
M = dict(
    bg         = "white",
    grid       = "#e2e8f0",
    price      = "#1d4ed8",
    support    = "#15803d",
    resistance = "#b91c1c",
    regression = "#ea580c",
    breakout   = "#ca8a04",
    volume     = "#93c5fd",
    vol_spike  = "#1d4ed8",
    rsi        = "#7c3aed",
    macd       = "#1d4ed8",
    signal_ln  = "#b91c1c",
    hist_pos   = "#15803d",
    hist_neg   = "#b91c1c",
    atr        = "#b45309",
    text       = "#1e293b",
    axis       = "#475569",
    spine      = "#cbd5e1",
)

# ─── Matplotlib helpers ───────────────────────────────────────────────────────

def _fig_to_png(fig: plt.Figure) -> bytes:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=DPI, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    buf.seek(0)
    data = buf.read()
    plt.close(fig)
    return data


def _png_to_rl(png: bytes, width: float, height: Optional[float] = None) -> RLImage:
    img = RLImage(io.BytesIO(png))
    aspect = img.drawHeight / img.drawWidth
    img.drawWidth  = width
    img.drawHeight = height if height else width * aspect
    return img


def _mpl_base(nrows=1, ratios=None, h_total=3.3) -> tuple:
    """Create a styled figure with 1-3 subplots sharing the x-axis."""
    fig, axes = plt.subplots(
        nrows, 1,
        figsize=(9.5, h_total),
        gridspec_kw={"height_ratios": ratios or [1] * nrows},
        sharex=(nrows > 1),
    )
    if nrows == 1:
        axes = [axes]
    for ax in axes:
        ax.set_facecolor(M["bg"])
        ax.grid(True, color=M["grid"], linewidth=0.6, linestyle="--", alpha=0.8)
        ax.tick_params(colors=M["axis"], labelsize=7)
        for sp in ax.spines.values():
            sp.set_color(M["spine"])
            sp.set_linewidth(0.6)
    fig.patch.set_facecolor(M["bg"])
    fig.subplots_adjust(hspace=0.08)
    return fig, axes


def _format_dates(ax, n: int):
    if n <= 30:
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))
    elif n <= 120:
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%b '%y"))
    else:
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    plt.setp(ax.get_xticklabels(), rotation=30, ha="right", fontsize=6)


def _safe_dates(df: pd.DataFrame) -> pd.Series:
    return pd.to_datetime(df["date"], errors="coerce")


# ─── ReportLab styles ─────────────────────────────────────────────────────────

def _styles() -> dict:
    base = getSampleStyleSheet()
    def S(name, **kw):
        return ParagraphStyle(name, parent=base["Normal"], **kw)

    return dict(
        title     = S("Title2",    fontName="Helvetica-Bold", fontSize=24, leading=30, textColor=C_NAVY,  alignment=TA_CENTER, spaceBefore=0,  spaceAfter=8),
        subtitle  = S("Sub2",      fontName="Helvetica",      fontSize=13, leading=17, textColor=C_SLATE, alignment=TA_CENTER, spaceBefore=4,  spaceAfter=6),
        h1        = S("H1",        fontName="Helvetica-Bold", fontSize=15, leading=19, textColor=C_NAVY,  spaceBefore=14, spaceAfter=5),
        h2        = S("H2",        fontName="Helvetica-Bold", fontSize=11, leading=14, textColor=C_NAVY,  spaceBefore=9,  spaceAfter=4),
        h3        = S("H3",        fontName="Helvetica-Bold", fontSize=9,  leading=12, textColor=C_SLATE, spaceBefore=6,  spaceAfter=3),
        body      = S("Body2",     fontName="Helvetica",      fontSize=8,  leading=12, textColor=C_SLATE, spaceAfter=3),
        small     = S("Small2",    fontName="Helvetica",      fontSize=7,  leading=10, textColor=C_MUTED),
        disclaimer= S("Disc2",     fontName="Helvetica-Oblique", fontSize=6.5, leading=10, textColor=C_MUTED,
                       alignment=TA_JUSTIFY, spaceBefore=6),
        label     = S("Label2",    fontName="Helvetica-Bold", fontSize=7.5, leading=10, textColor=C_NAVY),
        center    = S("Center2",   fontName="Helvetica",      fontSize=8,  leading=12, alignment=TA_CENTER, textColor=C_SLATE),
        edu_head  = S("EduHead",   fontName="Helvetica-Bold", fontSize=9,  leading=12, textColor=C_NAVY,  spaceBefore=7, spaceAfter=3),
        edu_body  = S("EduBody",   fontName="Helvetica",      fontSize=7.5, leading=11, textColor=C_SLATE, spaceAfter=2),
    )


# ─── Footer / header on every page ────────────────────────────────────────────

def _make_page_callback(gen_time: str):
    def _on_page(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 6.5)
        canvas.setFillColor(C_MUTED)
        canvas.drawString(MARGIN, 0.42 * inch,
                          f"Stock Pattern Engine v{TEMPLATE_VERSION}  |  Generated: {gen_time}")
        canvas.drawRightString(PAGE_W - MARGIN, 0.42 * inch, f"Page {doc.page}")
        canvas.setFont("Helvetica-Oblique", 5.5)
        canvas.drawCentredString(PAGE_W / 2, 0.27 * inch, "Not financial advice. Educational use only.")
        canvas.restoreState()
    return _on_page


# ─── Cover Page ───────────────────────────────────────────────────────────────

def _build_cover(elements: list, response: AnalysisResponse, ST: dict, gen_time: str = ""):
    elements.append(Spacer(1, 1.4 * inch))

    # Logo line
    elements.append(HRFlowable(width=CONTENT_W, thickness=3,
                                color=C_NAVY, spaceAfter=14))
    elements.append(Paragraph("Stock Pattern Engine", ST["title"]))
    elements.append(Paragraph(
        "Technical Pattern Recognition + Risk-Scored Trade Plan", ST["subtitle"]
    ))
    elements.append(HRFlowable(width=CONTENT_W, thickness=1,
                                color=C_MED, spaceBefore=8, spaceAfter=20))

    # Metadata block
    meta = [
        ["Report Generated:", gen_time],
        ["Template Version:", TEMPLATE_VERSION],
        ["Tickers Analysed:", str(response.tickers_analyzed)],
        ["Session ID:", response.session_id[:16] + "..."],
    ]
    tbl = Table(meta, colWidths=[1.6 * inch, CONTENT_W - 1.6 * inch])
    tbl.setStyle(TableStyle([
        ("FONTNAME",  (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE",  (0, 0), (-1, -1), 9),
        ("FONTNAME",  (0, 0), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), C_NAVY),
        ("TEXTCOLOR", (1, 0), (1, -1), C_SLATE),
        ("TOPPADDING",    (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(tbl)
    elements.append(Spacer(1, 20))

    # Tickers list
    elements.append(Paragraph("Tickers in this report:", ST["h3"]))
    tickers_str = "  •  ".join(r.ticker for r in response.results)
    elements.append(Paragraph(tickers_str, ST["body"]))
    elements.append(Spacer(1, 30))

    elements.append(HRFlowable(width=CONTENT_W, thickness=1, color=C_MED, spaceAfter=10))
    elements.append(Paragraph(DISCLAIMER, ST["disclaimer"]))
    elements.append(PageBreak())


# ─── Executive Summary ────────────────────────────────────────────────────────

def _risk_color(risk: str):
    return {
        RiskLevel.LOW.value:    (C_GREEN,  C_LGREEN),
        RiskLevel.MEDIUM.value: (C_AMBER,  C_LAMBER),
        RiskLevel.HIGH.value:   (C_RED,    C_LRED),
    }.get(risk, (C_SLATE, C_LIGHT))


def _signal_color(sig: str):
    return {
        TradeSignal.BUY.value:   C_GREEN,
        TradeSignal.SELL.value:  C_RED,
        TradeSignal.WATCH.value: C_AMBER,
    }.get(sig, C_SLATE)


def _summary_table(response: AnalysisResponse, ST: dict) -> Table:
    headers = [
        "Ticker", "Pattern", "Direction", "Conf.", "Risk",
        "Signal", "Entry", "Stop", "TP-1", "Upside %", "Hold",
    ]
    # Proportional weights scaled to fit exactly within CONTENT_W
    _w = [0.55, 1.30, 0.70, 0.42, 0.50, 0.52, 0.65, 0.65, 0.65, 0.55, 0.50]
    col_w = [w / sum(_w) * CONTENT_W for w in _w]

    rows = [headers]
    style_cmds = [
        ("BACKGROUND",   (0, 0), (-1, 0), C_NAVY),
        ("TEXTCOLOR",    (0, 0), (-1, 0), C_WHITE),
        ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",     (0, 0), (-1, -1), 7.5),
        ("ALIGN",        (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",   (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [C_WHITE, C_LIGHT]),
        ("GRID",         (0, 0), (-1, -1), 0.3, C_MED),
    ]

    for r_idx, res in enumerate(response.results, start=1):
        tp = res.top_pattern
        rk = res.risk_assessment
        tr = res.trade_recommendation

        pat   = tp.pattern_type.value.replace("_", " ").title() if tp else "—"
        dirn  = tp.trend_direction.value.title() if tp else "—"
        conf  = f"{tp.confidence_score:.0f}/100" if tp else "—"
        risk  = rk.risk_score.value if rk else "—"
        sig   = tr.signal.value if tr else "WATCH"
        entry = f"${tr.entry_price:.2f}" if tr else "—"
        stop  = f"${tr.stop_loss:.2f}" if tr else "—"
        tp1   = f"${tr.take_profit_1:.2f}" if tr else "—"
        up    = f"{rk.expected_upside_pct:.1f}%" if rk else "—"
        hold  = rk.holding_time.value if rk else "—"

        rows.append([res.ticker, pat, dirn, conf, risk, sig, entry, stop, tp1, up, hold])

        # Risk cell colour
        if rk:
            fg, bg = _risk_color(rk.risk_score.value)
            style_cmds += [
                ("BACKGROUND", (4, r_idx), (4, r_idx), bg),
                ("TEXTCOLOR",  (4, r_idx), (4, r_idx), fg),
                ("FONTNAME",   (4, r_idx), (4, r_idx), "Helvetica-Bold"),
            ]
        # Signal cell colour
        if tr:
            style_cmds += [
                ("TEXTCOLOR",  (5, r_idx), (5, r_idx), _signal_color(tr.signal.value)),
                ("FONTNAME",   (5, r_idx), (5, r_idx), "Helvetica-Bold"),
            ]
        # Direction colour
        if tp:
            dc = C_GREEN if tp.trend_direction == TrendDirection.BULLISH else (
                 C_RED if tp.trend_direction == TrendDirection.BEARISH else C_SLATE)
            style_cmds += [("TEXTCOLOR", (2, r_idx), (2, r_idx), dc),
                           ("FONTNAME",  (2, r_idx), (2, r_idx), "Helvetica-Bold")]

    tbl = Table(rows, colWidths=col_w)
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


def _risk_pie_chart(response: AnalysisResponse) -> bytes:
    try:
        counts = {RiskLevel.LOW.value: 0, RiskLevel.MEDIUM.value: 0, RiskLevel.HIGH.value: 0}
        for res in response.results:
            if res.risk_assessment:
                counts[res.risk_assessment.risk_score.value] += 1
        labels = [k for k, v in counts.items() if v > 0]
        vals   = [v for v in counts.values() if v > 0]
        clrs   = [{"LOW": "#15803d", "MEDIUM": "#b45309", "HIGH": "#b91c1c"}[l] for l in labels]

        fig, ax = plt.subplots(figsize=(3.8, 2.8))
        fig.patch.set_facecolor("white")
        ax.set_facecolor("white")
        if vals:
            wedges, texts, autotexts = ax.pie(
                vals, labels=labels, colors=clrs, autopct="%1.0f%%",
                startangle=90, pctdistance=0.78,
                textprops={"fontsize": 8, "color": M["text"]},
            )
            for at in autotexts:
                at.set_fontsize(7.5)
                at.set_color("white")
                at.set_fontweight("bold")
        else:
            ax.text(0.5, 0.5, "No risk data", ha="center", va="center",
                    fontsize=9, color=M["axis"], transform=ax.transAxes)
        ax.set_title("Risk Distribution", fontsize=9, color=M["text"], fontweight="bold", pad=6)
        return _fig_to_png(fig)
    except Exception:
        return b""


def _confidence_bar_chart(response: AnalysisResponse) -> bytes:
    try:
        tickers = [r.ticker for r in response.results]
        confs   = [r.top_pattern.confidence_score if r.top_pattern else 0
                   for r in response.results]
        bar_clrs = [
            "#15803d" if c >= 70 else ("#b45309" if c >= 50 else "#b91c1c")
            for c in confs
        ]

        fig, ax = plt.subplots(figsize=(max(4.5, len(tickers) * 1.1), 2.8))
        fig.patch.set_facecolor("white")
        ax.set_facecolor("white")
        bars = ax.bar(tickers, confs, color=bar_clrs, edgecolor="white",
                      linewidth=0.5, width=0.55)
        for bar, val in zip(bars, confs):
            ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1.5,
                    f"{val:.0f}", ha="center", va="bottom",
                    fontsize=7.5, fontweight="bold", color=M["text"])
        ax.set_ylim(0, 105)
        ax.axhline(70, color="#15803d", linewidth=0.8, linestyle="--", alpha=0.6, label="High (70)")
        ax.axhline(50, color="#b45309", linewidth=0.8, linestyle="--", alpha=0.6, label="Med (50)")
        ax.set_ylabel("Confidence Score", fontsize=7.5, color=M["axis"])
        ax.set_title("Pattern Confidence by Ticker", fontsize=9, color=M["text"],
                     fontweight="bold", pad=6)
        ax.tick_params(colors=M["axis"], labelsize=7.5)
        ax.legend(fontsize=6.5, loc="upper right", framealpha=0.7)
        ax.grid(axis="y", color=M["grid"], linewidth=0.6, linestyle="--")
        ax.set_facecolor("white")
        for sp in ax.spines.values():
            sp.set_color(M["spine"])
            sp.set_linewidth(0.6)
        fig.patch.set_facecolor("white")
        return _fig_to_png(fig)
    except Exception:
        return b""


def _build_executive_summary(elements: list, response: AnalysisResponse, ST: dict):
    elements.append(Paragraph("Executive Summary", ST["h1"]))
    elements.append(HRFlowable(width=CONTENT_W, thickness=1, color=C_MED, spaceAfter=8))
    elements.append(_summary_table(response, ST))
    elements.append(Spacer(1, 12))

    # Side-by-side charts
    pie_png  = _risk_pie_chart(response)
    bar_png  = _confidence_bar_chart(response)
    half     = (CONTENT_W - 8) / 2

    chart_row = Table(
        [[_png_to_rl(pie_png, half, CHART_SUMMARY),
          _png_to_rl(bar_png, half, CHART_SUMMARY)]],
        colWidths=[half, half],
        hAlign="LEFT",
    )
    chart_row.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"),
                                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                                    ("RIGHTPADDING", (0, 0), (-1, -1), 0)]))
    elements.append(chart_row)
    elements.append(PageBreak())


# ─── Per-Ticker Charts ────────────────────────────────────────────────────────

def _price_chart(df: pd.DataFrame, res: TickerAnalysis) -> bytes:
    try:
        dates  = _safe_dates(df)
        closes = pd.to_numeric(df["close"], errors="coerce")
        n      = len(df)

        fig, ax = plt.subplots(figsize=(9.5, CHART_MAIN / inch))
        fig.patch.set_facecolor(M["bg"])
        ax.set_facecolor(M["bg"])

        # Price line
        ax.plot(dates, closes, color=M["price"], linewidth=1.4, label="Close", zorder=3)

        # Fill under price
        ax.fill_between(dates, closes, closes.min() * 0.995,
                        alpha=0.06, color=M["price"])

        # Best-fit regression overlay
        x_num = np.arange(len(closes))
        valid_mask = ~np.isnan(closes.values)
        if valid_mask.sum() >= 10:
            try:
                coeffs = np.polyfit(x_num[valid_mask], closes.values[valid_mask], 1)
                y_reg = np.polyval(coeffs, x_num)
                ax.plot(dates, y_reg, color=M["regression"], linewidth=1.0,
                        linestyle="-.", alpha=0.6, label="Linear fit", zorder=3)
            except Exception:
                pass

        # Overlay trendlines from top pattern
        tp = res.top_pattern
        if tp:
            # Support line
            ax.annotate("", xy=(dates.iloc[-1], tp.support_line.end_price),
                        xytext=(dates.iloc[0], tp.support_line.start_price),
                        arrowprops=dict(arrowstyle="-", color=M["support"],
                                       lw=1.4, linestyle="--"),
                        annotation_clip=False)
            ax.plot([dates.iloc[0], dates.iloc[-1]],
                    [tp.support_line.start_price, tp.support_line.end_price],
                    color=M["support"], linewidth=1.3, linestyle="--",
                    alpha=0.8, label="Support", zorder=4)
            # Resistance line
            ax.plot([dates.iloc[0], dates.iloc[-1]],
                    [tp.resistance_line.start_price, tp.resistance_line.end_price],
                    color=M["resistance"], linewidth=1.3, linestyle="--",
                    alpha=0.8, label="Resistance", zorder=4)
            # Breakout level
            ax.axhline(tp.breakout_level, color=M["breakout"], linewidth=1.0,
                       linestyle=":", alpha=0.9, label=f"Breakout ${tp.breakout_level:.2f}", zorder=4)

        ax.set_title(f"{res.ticker} — Price History (Close)",
                     fontsize=9.5, color=M["text"], fontweight="bold", pad=6)
        ax.set_ylabel("Price ($)", fontsize=7.5, color=M["axis"])
        ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("$%.2f"))
        ax.legend(fontsize=6.5, loc="upper left", framealpha=0.75)
        ax.grid(True, color=M["grid"], linewidth=0.5, linestyle="--")
        for sp in ax.spines.values():
            sp.set_color(M["spine"]); sp.set_linewidth(0.6)
        ax.tick_params(colors=M["axis"], labelsize=7)
        _format_dates(ax, n)
        fig.tight_layout(pad=0.5)
        return _fig_to_png(fig)
    except Exception:
        return b""


def _volume_chart(df: pd.DataFrame, res: TickerAnalysis) -> bytes:
    try:
        dates   = _safe_dates(df)
        volumes = pd.to_numeric(df["volume"], errors="coerce").fillna(0)
        avg_vol = volumes.rolling(20, min_periods=1).mean()

        # Identify spike candles (>=1.5x avg)
        spikes = volumes >= avg_vol * 1.5
        bar_colors = [M["vol_spike"] if s else M["volume"] for s in spikes]

        fig, ax = plt.subplots(figsize=(9.5, CHART_IND / inch))
        fig.patch.set_facecolor(M["bg"])
        ax.set_facecolor(M["bg"])

        ax.bar(dates, volumes / 1e6, color=bar_colors, width=0.6, alpha=0.85)
        ax.plot(dates, avg_vol / 1e6, color=M["price"], linewidth=0.9,
                linestyle="--", label="20-bar avg", alpha=0.7)

        ax.set_title(f"{res.ticker} — Volume (M shares)", fontsize=9.5,
                     color=M["text"], fontweight="bold", pad=6)
        ax.set_ylabel("Volume (M)", fontsize=7.5, color=M["axis"])
        ax.legend(fontsize=6.5, loc="upper left", framealpha=0.75)
        ax.grid(True, color=M["grid"], linewidth=0.5, linestyle="--")
        for sp in ax.spines.values():
            sp.set_color(M["spine"]); sp.set_linewidth(0.6)
        ax.tick_params(colors=M["axis"], labelsize=7)
        _format_dates(ax, len(df))
        fig.tight_layout(pad=0.5)
        return _fig_to_png(fig)
    except Exception:
        return b""


def _indicator_panel(df: pd.DataFrame, ticker: str) -> bytes:
    try:
        return _indicator_panel_inner(df, ticker)
    except Exception:
        return b""


def _indicator_panel_inner(df: pd.DataFrame, ticker: str) -> bytes:
    dates = _safe_dates(df)
    n     = len(df)

    has_rsi  = "RSI"  in df.columns
    has_macd = "MACD" in df.columns and "MACD_signal" in df.columns
    has_atr  = "ATR"  in df.columns

    n_panels = sum([has_rsi, has_macd, has_atr])
    if n_panels == 0:
        return b""

    ratios = []
    if has_rsi:  ratios.append(1.0)
    if has_macd: ratios.append(1.2)
    if has_atr:  ratios.append(0.8)

    fig, axes = plt.subplots(
        n_panels, 1,
        figsize=(9.5, (CHART_IND / inch) * n_panels),
        gridspec_kw={"height_ratios": ratios},
        sharex=True,
    )
    if n_panels == 1:
        axes = [axes]

    axidx = 0

    # RSI
    if has_rsi:
        ax = axes[axidx]; axidx += 1
        rsi = pd.to_numeric(df["RSI"], errors="coerce")
        ax.plot(dates, rsi, color=M["rsi"], linewidth=1.1, label="RSI")
        ax.axhline(70, color=M["signal_ln"], linewidth=0.8,
                   linestyle="--", alpha=0.7, label="OB (70)")
        ax.axhline(30, color=M["hist_pos"],  linewidth=0.8,
                   linestyle="--", alpha=0.7, label="OS (30)")
        ax.fill_between(dates, rsi, 70, where=(rsi >= 70),
                        alpha=0.15, color=M["signal_ln"])
        ax.fill_between(dates, rsi, 30, where=(rsi <= 30),
                        alpha=0.15, color=M["hist_pos"])
        ax.set_ylim(0, 100)
        ax.set_ylabel("RSI", fontsize=7, color=M["axis"])
        ax.legend(fontsize=5.5, loc="upper right", framealpha=0.7)
        ax.tick_params(colors=M["axis"], labelsize=6.5)
        ax.set_facecolor(M["bg"])
        ax.grid(True, color=M["grid"], linewidth=0.5, linestyle="--")
        for sp in ax.spines.values(): sp.set_color(M["spine"]); sp.set_linewidth(0.5)

    # MACD
    if has_macd:
        ax = axes[axidx]; axidx += 1
        macd    = pd.to_numeric(df["MACD"],        errors="coerce")
        sig_ln  = pd.to_numeric(df.get("MACD_signal", df["MACD"] * 0), errors="coerce")
        hist    = pd.to_numeric(df.get("MACD_histogram", macd - sig_ln), errors="coerce")

        hist_colors = [M["hist_pos"] if v >= 0 else M["hist_neg"]
                       for v in hist.fillna(0)]
        ax.bar(dates, hist, color=hist_colors, alpha=0.6, width=0.6, label="Histogram")
        ax.plot(dates, macd,   color=M["macd"],     linewidth=1.0, label="MACD")
        ax.plot(dates, sig_ln, color=M["signal_ln"],linewidth=0.9,
                linestyle="--", label="Signal")
        ax.axhline(0, color=M["axis"], linewidth=0.5, alpha=0.5)
        ax.set_ylabel("MACD", fontsize=7, color=M["axis"])
        ax.legend(fontsize=5.5, loc="upper right", framealpha=0.7)
        ax.tick_params(colors=M["axis"], labelsize=6.5)
        ax.set_facecolor(M["bg"])
        ax.grid(True, color=M["grid"], linewidth=0.5, linestyle="--")
        for sp in ax.spines.values(): sp.set_color(M["spine"]); sp.set_linewidth(0.5)

    # ATR
    if has_atr:
        ax = axes[axidx]; axidx += 1
        atr = pd.to_numeric(df["ATR"], errors="coerce")
        ax.plot(dates, atr, color=M["atr"], linewidth=1.0, label="ATR (14)")
        ax.fill_between(dates, atr, alpha=0.12, color=M["atr"])
        ax.set_ylabel("ATR", fontsize=7, color=M["axis"])
        ax.legend(fontsize=5.5, loc="upper right", framealpha=0.7)
        ax.tick_params(colors=M["axis"], labelsize=6.5)
        ax.set_facecolor(M["bg"])
        ax.grid(True, color=M["grid"], linewidth=0.5, linestyle="--")
        for sp in ax.spines.values(): sp.set_color(M["spine"]); sp.set_linewidth(0.5)

    axes[0].set_title(f"{ticker} — Technical Indicators", fontsize=9.5,
                      color=M["text"], fontweight="bold", pad=6)
    _format_dates(axes[-1], n)
    fig.patch.set_facecolor(M["bg"])
    fig.subplots_adjust(hspace=0.10)
    fig.tight_layout(pad=0.4)
    return _fig_to_png(fig)


def _pattern_overlay_chart(df: pd.DataFrame, res: TickerAnalysis) -> bytes:
    """Draw pattern-specific geometry on a zoomed price chart."""
    try:
        return _pattern_overlay_chart_inner(df, res)
    except Exception:
        return b""


def _pattern_overlay_chart_inner(df: pd.DataFrame, res: TickerAnalysis) -> bytes:
    tp = res.top_pattern
    if not tp:
        return b""

    dates  = _safe_dates(df)
    closes = pd.to_numeric(df["close"],  errors="coerce")
    highs  = pd.to_numeric(df["high"],   errors="coerce")
    lows   = pd.to_numeric(df["low"],    errors="coerce")
    n      = len(df)

    fig, ax = plt.subplots(figsize=(9.5, CHART_PATTERN / inch))
    fig.patch.set_facecolor(M["bg"])
    ax.set_facecolor(M["bg"])

    # Shade the pattern window with light fill
    try:
        s_idx = df[df["date"].astype(str) >= str(tp.start_date)].index[0]
    except Exception:
        s_idx = 0
    ax.axvspan(dates.iloc[s_idx], dates.iloc[-1],
               alpha=0.06, color=M["breakout"], label="Pattern window")

    # Price + wick candle-lite bars
    ax.plot(dates, closes, color=M["price"], linewidth=1.3,
            label="Close", zorder=3)
    ax.vlines(dates, lows, highs, color=M["grid"], linewidth=0.5,
              alpha=0.5, label="Hi/Lo range")

    ptype = tp.pattern_type.value

    # Draw support line
    ax.plot([dates.iloc[0], dates.iloc[-1]],
            [tp.support_line.start_price, tp.support_line.end_price],
            color=M["support"], linewidth=1.6, linestyle="--",
            alpha=0.85, label="Support", zorder=5)
    # Draw resistance line
    ax.plot([dates.iloc[0], dates.iloc[-1]],
            [tp.resistance_line.start_price, tp.resistance_line.end_price],
            color=M["resistance"], linewidth=1.6, linestyle="--",
            alpha=0.85, label="Resistance", zorder=5)

    # ── Pattern-specific overlays ─────────────────────────────────────────────

    if "cup" in ptype:
        # Polynomial U-curve overlay on lows
        x = np.arange(n, dtype=float)
        try:
            coeffs = np.polyfit(x, lows.values, 2)
            y_poly = np.polyval(coeffs, x)
            ax.plot(dates, y_poly, color=M["regression"],
                    linewidth=2.0, linestyle=":", label="Poly fit (cup)", zorder=6)
        except Exception:
            pass
        # Annotate cup and handle regions
        mid = n // 2
        ax.annotate("Cup", xy=(dates.iloc[mid], lows.min()),
                    xytext=(dates.iloc[mid], lows.min() - lows.std() * 0.8),
                    fontsize=7.5, color=M["regression"], fontweight="bold",
                    arrowprops=dict(arrowstyle="->", color=M["regression"], lw=0.8))
        if n > 10:
            ax.annotate("Handle", xy=(dates.iloc[-5], closes.iloc[-5]),
                        xytext=(dates.iloc[-8], closes.iloc[-8] - closes.std() * 0.5),
                        fontsize=7.5, color=M["breakout"], fontweight="bold",
                        arrowprops=dict(arrowstyle="->", color=M["breakout"], lw=0.8))

    elif "head_and_shoulders" in ptype or "inverse_head" in ptype:
        # Mark 3 peaks (or troughs for inverse)
        inv = "inverse" in ptype
        arr = lows.values if inv else highs.values
        prominence = arr.std() * 0.4
        if inv:
            pks, _ = find_peaks(-arr, distance=n // 6, prominence=prominence)
        else:
            pks, _ = find_peaks(arr, distance=n // 6, prominence=prominence)
        for i, pk in enumerate(pks[:3]):
            label_map = ["Left Shoulder", "Head", "Right Shoulder"]
            lbl = label_map[i] if i < 3 else ""
            y_pt = arr[pk]
            offset = -arr.std() * 0.5 if inv else arr.std() * 0.5
            ax.annotate(lbl, xy=(dates.iloc[pk], y_pt),
                        xytext=(dates.iloc[pk], y_pt + offset),
                        fontsize=6.5, color=M["breakout"], fontweight="bold",
                        ha="center",
                        arrowprops=dict(arrowstyle="->", color=M["breakout"], lw=0.7))

    elif "double" in ptype or "triple" in ptype:
        # Mark equal peaks / troughs
        inv = "bottom" in ptype
        arr = lows.values if inv else highs.values
        pks, _ = find_peaks(-arr if inv else arr,
                            distance=n // 8, prominence=arr.std() * 0.3)
        n_peaks = 2 if "double" in ptype else 3
        for pk in pks[:n_peaks]:
            ax.axvline(dates.iloc[pk], color=M["breakout"],
                       linewidth=0.9, linestyle=":", alpha=0.8)
            ax.annotate("Peak" if not inv else "Trough",
                        xy=(dates.iloc[pk], arr[pk]),
                        xytext=(dates.iloc[pk], arr[pk] + arr.std() * 0.4 * (1 if not inv else -1)),
                        fontsize=6, color=M["breakout"], ha="center",
                        arrowprops=dict(arrowstyle="->", color=M["breakout"], lw=0.6))

    elif "wedge" in ptype or "triangle" in ptype or "rectangle" in ptype or "flag" in ptype or "pennant" in ptype:
        # Lines already drawn via support/resistance above; add apex annotation
        apex_x = dates.iloc[-1]
        apex_y = (tp.support_line.end_price + tp.resistance_line.end_price) / 2
        ax.annotate("Apex →", xy=(apex_x, apex_y),
                    fontsize=7, color=M["breakout"], va="center",
                    fontweight="bold")

    # Breakout level
    ax.axhline(tp.breakout_level, color=M["breakout"], linewidth=1.2,
               linestyle=":", alpha=0.9,
               label=f"Breakout ${tp.breakout_level:.2f}", zorder=6)

    pattern_label = ptype.replace("_", " ").title()
    ax.set_title(
        f"{res.ticker} — Pattern: {pattern_label}  "
        f"(Confidence {tp.confidence_score:.0f}/100, {tp.trend_direction.value})",
        fontsize=9, color=M["text"], fontweight="bold", pad=6,
    )
    ax.set_ylabel("Price ($)", fontsize=7.5, color=M["axis"])
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("$%.2f"))
    ax.legend(fontsize=6.5, loc="upper left", framealpha=0.75, ncol=2)
    ax.grid(True, color=M["grid"], linewidth=0.5, linestyle="--")
    for sp in ax.spines.values():
        sp.set_color(M["spine"]); sp.set_linewidth(0.6)
    ax.tick_params(colors=M["axis"], labelsize=7)
    _format_dates(ax, n)
    fig.tight_layout(pad=0.5)
    return _fig_to_png(fig)


# ─── Per-Ticker Report Section ────────────────────────────────────────────────

def _signal_badge_text(sig: str) -> str:
    return {"BUY": "● BUY", "SELL": "● SELL", "WATCH": "● WATCH"}.get(sig, sig)


def _risk_row(label, val, st):
    return [Paragraph(label, st["label"]), Paragraph(str(val), st["body"])]


def _build_ticker_section(
    elements: list,
    res: TickerAnalysis,
    df: pd.DataFrame,
    ST: dict,
):
    elements.append(Paragraph(f"Ticker: {res.ticker}", ST["h1"]))
    elements.append(HRFlowable(width=CONTENT_W, thickness=1.5,
                                color=C_NAVY, spaceAfter=6))

    tp = res.top_pattern
    rk = res.risk_assessment
    tr = res.trade_recommendation

    # ── Metadata bar ──────────────────────────────────────────────────────────
    meta_data = [
        ["Current Price:",  f"${res.current_price:.2f}",
         "Timeframe:",      f"{res.timeframe_start}  →  {res.timeframe_end}"],
        ["RSI:",            f"{res.current_rsi:.1f}" if res.current_rsi else "—",
         "MACD:",           f"{res.current_macd:.4f}" if res.current_macd else "—"],
    ]
    meta_tbl = Table(meta_data,
                     colWidths=[1.0 * inch, 1.2 * inch, 1.0 * inch, CONTENT_W - 3.2 * inch])
    meta_tbl.setStyle(TableStyle([
        ("FONTNAME",   (0, 0), (-1, -1), "Helvetica"),
        ("FONTNAME",   (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",   (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 8),
        ("TEXTCOLOR",  (0, 0), (-1, -1), C_SLATE),
        ("TEXTCOLOR",  (0, 0), (0, -1), C_NAVY),
        ("TEXTCOLOR",  (2, 0), (2, -1), C_NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    elements.append(meta_tbl)
    elements.append(Spacer(1, 8))

    # ── A: Price chart ────────────────────────────────────────────────────────
    elements.append(Paragraph("A) Price History + Trendline Overlays", ST["h2"]))
    price_png = _price_chart(df, res)
    elements.append(_png_to_rl(price_png, CONTENT_W, CHART_MAIN))
    elements.append(Spacer(1, 6))

    # ── B: Volume ─────────────────────────────────────────────────────────────
    elements.append(Paragraph("B) Volume Confirmation", ST["h2"]))
    vol_png = _volume_chart(df, res)
    elements.append(_png_to_rl(vol_png, CONTENT_W, CHART_IND))
    elements.append(Spacer(1, 6))

    # ── C: Indicators ─────────────────────────────────────────────────────────
    ind_png = _indicator_panel(df, res.ticker)
    if ind_png:
        elements.append(Paragraph("C) Technical Indicator Panel (RSI / MACD / ATR)", ST["h2"]))
        n_panels = sum([
            "RSI" in df.columns,
            "MACD" in df.columns,
            "ATR" in df.columns,
        ])
        elements.append(_png_to_rl(ind_png, CONTENT_W, CHART_IND * n_panels))
        elements.append(Spacer(1, 6))

    # ── D: Pattern overlay + trade details ────────────────────────────────────
    if tp:
        elements.append(Paragraph(
            f"D) Pattern Visualisation — {tp.pattern_type.value.replace('_',' ').title()}",
            ST["h2"],
        ))
        pat_png = _pattern_overlay_chart(df, res)
        if pat_png:
            elements.append(_png_to_rl(pat_png, CONTENT_W, CHART_PATTERN))
        elements.append(Spacer(1, 8))

        # Pattern metadata table
        pat_meta = [
            ["Pattern Type:", tp.pattern_type.value.replace("_", " ").title(),
             "Direction:",    tp.trend_direction.value],
            ["Confidence:",   f"{tp.confidence_score:.1f}/100",
             "Breakout:",     f"${tp.breakout_level:.2f}"],
            ["Support slope:", f"{tp.slope_support:.5f}",
             "Resistance slope:", f"{tp.slope_resistance:.5f}"],
            ["Volume surge:", f"{tp.volume_confirmation:.2f}×",
             "Vol confirmed:", "Yes" if tp.volume_confirmed else "No"],
            ["Volatility est.:", f"{tp.volatility_estimate:.3f} (ann.)",
             "Candles analysed:", str(tp.candles_analyzed)],
        ]
        if tp.raw_notes:
            pat_meta.append(["Notes:", tp.raw_notes, "", ""])

        pat_tbl = Table(pat_meta,
                        colWidths=[1.2*inch, 1.6*inch, 1.3*inch, CONTENT_W - 4.1*inch])
        pat_tbl.setStyle(TableStyle([
            ("FONTNAME",     (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME",     (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTNAME",     (2, 0), (2, -1), "Helvetica-Bold"),
            ("FONTSIZE",     (0, 0), (-1, -1), 8),
            ("TEXTCOLOR",    (0, 0), (-1, -1), C_SLATE),
            ("TEXTCOLOR",    (0, 0), (0, -1), C_NAVY),
            ("TEXTCOLOR",    (2, 0), (2, -1), C_NAVY),
            ("TOPPADDING",   (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 3),
            ("ROWBACKGROUNDS",(0, 0), (-1, -1), [C_WHITE, C_LIGHT]),
            ("GRID",         (0, 0), (-1, -1), 0.3, C_MED),
        ]))
        elements.append(pat_tbl)
        elements.append(Spacer(1, 8))

    # ── Trade Plan ────────────────────────────────────────────────────────────
    if tr and rk:
        elements.append(Paragraph("Trade Plan", ST["h2"]))
        sig_col = {
            TradeSignal.BUY.value:   C_GREEN,
            TradeSignal.SELL.value:  C_RED,
            TradeSignal.WATCH.value: C_AMBER,
        }.get(tr.signal.value, C_SLATE)

        plan_data = [
            ["Signal",       "Entry",              "Stop Loss",      "TP-1",
             "TP-2",         "TP-3",               "R/R",            "Pos. Size %"],
            [tr.signal.value,
             f"${tr.entry_price:.2f}",    f"${tr.stop_loss:.2f}",
             f"${tr.take_profit_1:.2f}",  f"${tr.take_profit_2:.2f}",
             f"${tr.take_profit_3:.2f}",  f"{tr.risk_reward_ratio:.2f}×",
             f"{tr.position_size_pct:.1f}%"],
        ]
        plan_tbl = Table(plan_data,
                         colWidths=[(CONTENT_W) / 8] * 8,
                         hAlign="LEFT")
        plan_tbl.setStyle(TableStyle([
            ("BACKGROUND",   (0, 0), (-1, 0), C_NAVY),
            ("TEXTCOLOR",    (0, 0), (-1, 0), C_WHITE),
            ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",     (0, 0), (-1, -1), 8),
            ("ALIGN",        (0, 0), (-1, -1), "CENTER"),
            ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING",   (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
            ("GRID",         (0, 0), (-1, -1), 0.3, C_MED),
            ("BACKGROUND",   (0, 1), (0, 1), C_LGREEN if tr.signal == TradeSignal.BUY
                                             else (C_LRED if tr.signal == TradeSignal.SELL
                                                   else C_LAMBER)),
            ("TEXTCOLOR",    (0, 1), (0, 1), sig_col),
            ("FONTNAME",     (0, 1), (0, 1), "Helvetica-Bold"),
        ]))
        elements.append(plan_tbl)
        elements.append(Spacer(1, 6))

        # Risk detail
        risk_row_data = [
            ["Risk Score:", f"{rk.risk_score.value} ({rk.risk_numeric:.0f}/100)",
             "Expected Upside:", f"{rk.expected_upside_pct:.1f}%",
             "Holding Time:", rk.holding_time.value],
            ["False Breakout %:", f"{rk.false_breakout_probability*100:.0f}%",
             "Expected Downside:", f"{rk.expected_downside_pct:.1f}%",
             "ATR used:", f"${tr.atr_used:.2f}"],
        ]
        risk_tbl = Table(risk_row_data,
                         colWidths=[1.3*inch, 1.1*inch, 1.4*inch, 0.9*inch, 1.0*inch, CONTENT_W - 5.7*inch])
        risk_tbl.setStyle(TableStyle([
            ("FONTNAME",     (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME",     (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTNAME",     (2, 0), (2, -1), "Helvetica-Bold"),
            ("FONTNAME",     (4, 0), (4, -1), "Helvetica-Bold"),
            ("FONTSIZE",     (0, 0), (-1, -1), 7.5),
            ("TEXTCOLOR",    (0, 0), (-1, -1), C_SLATE),
            ("TEXTCOLOR",    (0, 0), (0, -1), C_NAVY),
            ("TEXTCOLOR",    (2, 0), (2, -1), C_NAVY),
            ("TEXTCOLOR",    (4, 0), (4, -1), C_NAVY),
            ("TOPPADDING",   (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 3),
            ("ROWBACKGROUNDS",(0, 0), (-1, -1), [C_LIGHT, C_WHITE]),
            ("GRID",         (0, 0), (-1, -1), 0.3, C_MED),
        ]))
        elements.append(risk_tbl)
        elements.append(Spacer(1, 6))

        # Summary explanation
        if tr.summary_explanation:
            elements.append(Paragraph(tr.summary_explanation, ST["small"]))

    # All detected patterns list
    if len(res.patterns_detected) > 1:
        elements.append(Spacer(1, 8))
        elements.append(Paragraph("All Detected Patterns", ST["h3"]))
        apd = [["Pattern", "Direction", "Confidence", "Breakout", "Vol. Confirmed"]]
        for p in res.patterns_detected:
            apd.append([
                p.pattern_type.value.replace("_", " ").title(),
                p.trend_direction.value,
                f"{p.confidence_score:.1f}/100",
                f"${p.breakout_level:.2f}",
                "Yes" if p.volume_confirmed else "No",
            ])
        all_pat_tbl = Table(apd, colWidths=[2.2*inch, 1.0*inch, 1.0*inch, 1.0*inch, 1.0*inch])
        all_pat_tbl.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), C_SLATE),
            ("TEXTCOLOR",   (0, 0), (-1, 0), C_WHITE),
            ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, -1), 7.5),
            ("ALIGN",       (0, 0), (-1, -1), "CENTER"),
            ("TOPPADDING",  (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 3),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [C_WHITE, C_LIGHT]),
            ("GRID",        (0, 0), (-1, -1), 0.3, C_MED),
        ]))
        elements.append(all_pat_tbl)

    if not tp:
        elements.append(Paragraph(
            "No patterns met the minimum confidence threshold for this ticker. "
            "Consider uploading more rows (50+) or a different timeframe.",
            ST["body"],
        ))

    elements.append(PageBreak())


# ─── Education Page ───────────────────────────────────────────────────────────

EDU_CONTENT = {
    "Continuation Patterns": [
        ("Ascending Triangle",
         "Flat resistance + rising support. Bullish breakout expected above resistance. "
         "Math: resistance slope ≈ 0, support slope > 0; lines converge."),
        ("Descending Triangle",
         "Flat support + declining resistance. Bearish breakdown expected. "
         "Math: support slope ≈ 0, resistance slope < 0; lines converge."),
        ("Symmetrical Triangle",
         "Both trendlines converge toward apex. Breakout direction follows macro trend. "
         "Math: support slope > 0, resistance slope < 0."),
        ("Flags & Pennants",
         "Sharp 'pole' move followed by consolidation. Flag = parallel channel. "
         "Pennant = converging mini-triangle. Measured target = pole height projected from breakout."),
    ],
    "Reversal Patterns": [
        ("Head & Shoulders",
         "Three peaks: left shoulder < head > right shoulder. Bearish signal on neckline break. "
         "Math: pivot-high detection, shoulder symmetry tolerance ≤ 5%."),
        ("Inverse Head & Shoulders",
         "Mirror image — three troughs with middle lowest. Bullish signal on neckline break. "
         "Neckline = linear regression through peaks between troughs."),
        ("Double Top / Bottom",
         "Two equal peaks (top) or troughs (bottom) within 3% of each other, "
         "≥ 5 candles apart. Volume should decline on second peak (distribution)."),
        ("Triple Top / Bottom",
         "Three equal extremes. Higher statistical reliability than double. "
         "Measured move = pattern height projected from breakout level."),
    ],
    "Other Patterns": [
        ("Cup & Handle",
         "Rounded U-shaped base confirmed by degree-2 polynomial fit (R² > 0.65, concave-up). "
         "Handle = small pullback < 50% of cup depth. Breakout = close above rim level."),
        ("Rising Wedge (Bearish)",
         "Both trendlines slope up but converge. Support rises faster than resistance → exhaustion. "
         "Breakout expected below support trendline."),
        ("Falling Wedge (Bullish)",
         "Both trendlines slope down but converge. Resistance declines faster → deceleration. "
         "Breakout expected above resistance trendline."),
        ("Rectangles",
         "Both trendlines flat (|slope| < 0.008). Price consolidates between horizontal levels. "
         "Breakout direction follows the prior macro trend."),
    ],
}

HOW_TO_READ = [
    ("1. Identify the trend",
     "Before spotting a pattern, determine if price is in an uptrend, downtrend, or range. "
     "Use EMA-20, EMA-50, and SMA-200 relationships as macro filters."),
    ("2. Spot the pattern",
     "Look for the geometric structure: trendline touches, peak/trough sequences, "
     "consolidation zones. Require at least 2–3 pivots per trendline."),
    ("3. Mark support/resistance",
     "Draw the bounding lines. For linear patterns, use regression; "
     "for rounded patterns, use polynomial fit."),
    ("4. Confirm with volume",
     "Breakout volume should be ≥ 1.5× the 20-bar average. "
     "Low-volume breakouts have higher false-breakout probability."),
    ("5. Combine with indicators",
     "RSI below 70 for BUY signals; above 30 for SELL signals. "
     "MACD crossover aligned with pattern direction improves reliability."),
    ("6. Apply risk management",
     "Set stop-loss 1–1.5× ATR below the breakout support. "
     "Target minimum 2:1 reward-to-risk ratio."),
]

TIPS = [
    "High-probability setups: Inverse H&S, Double Bottom, Ascending Triangle in uptrend.",
    "Multi-timeframe confirmation significantly improves reliability (e.g. daily + 4H).",
    "Earnings/news events override technical patterns - check the earnings calendar.",
    "Patterns with R^2 > 0.85 on trendline fits have more reliable breakouts.",
    "Volume confirmation at the breakout candle reduces false-breakout probability by ~40%.",
]


def _build_education_page(elements: list, ST: dict):
    elements.append(Paragraph("Pattern Reference & Educational Guide", ST["h1"]))
    elements.append(HRFlowable(width=CONTENT_W, thickness=2, color=C_NAVY, spaceAfter=8))
    elements.append(Paragraph(
        "This section provides a reference for the chart patterns detected by the "
        "Stock Pattern Engine, along with the mathematical approach used for each.",
        ST["body"],
    ))
    elements.append(Spacer(1, 8))

    # Pattern reference tables
    for category, patterns in EDU_CONTENT.items():
        elements.append(Paragraph(category, ST["h2"]))
        hdr_style = ParagraphStyle(
            "EduTblHdr", fontName="Helvetica-Bold", fontSize=7.5,
            textColor=C_WHITE, leading=10,
        )
        name_style = ParagraphStyle(
            "EduTblName", fontName="Helvetica-Bold", fontSize=7.5,
            textColor=C_NAVY, leading=10,
        )
        desc_style = ParagraphStyle(
            "EduTblDesc", fontName="Helvetica", fontSize=7.5,
            textColor=C_SLATE, leading=11, wordWrap="LTR",
        )
        tbl_data = [[Paragraph("Pattern", hdr_style),
                     Paragraph("Description & Math", hdr_style)]]
        for name, desc in patterns:
            tbl_data.append([
                Paragraph(name, name_style),
                Paragraph(desc, desc_style),
            ])
        tbl = Table(tbl_data, colWidths=[1.7 * inch, CONTENT_W - 1.7 * inch])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), C_NAVY),
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [C_WHITE, C_LIGHT]),
            ("GRID",          (0, 0), (-1, -1), 0.3, C_MED),
        ]))
        elements.append(tbl)
        elements.append(Spacer(1, 8))

    # How to read
    elements.append(Paragraph("How to Read Chart Patterns", ST["h2"]))
    how_data = [[Paragraph(f"<b>{step}</b>", ST["label"]),
                 Paragraph(desc, ST["edu_body"])]
                for step, desc in HOW_TO_READ]
    how_tbl = Table(how_data, colWidths=[1.6 * inch, CONTENT_W - 1.6 * inch])
    how_tbl.setStyle(TableStyle([
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",   (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("ROWBACKGROUNDS",(0, 0), (-1, -1), [C_WHITE, C_LIGHT]),
        ("GRID",         (0, 0), (-1, -1), 0.3, C_MED),
    ]))
    elements.append(how_tbl)
    elements.append(Spacer(1, 10))

    # Practical tips
    elements.append(Paragraph("Practical Tips", ST["h2"]))
    for tip in TIPS:
        elements.append(Paragraph(f"◆  {tip}", ST["edu_body"]))

    elements.append(Spacer(1, 12))
    elements.append(HRFlowable(width=CONTENT_W, thickness=1, color=C_MED, spaceAfter=6))
    elements.append(Paragraph(DISCLAIMER, ST["disclaimer"]))


# ─── Main Entry Point ─────────────────────────────────────────────────────────

def generate_pdf_report(
    analysis_response: AnalysisResponse,
    dataframes: Dict[str, pd.DataFrame],
) -> bytes:
    """
    Generate a complete investor-grade PDF report.

    Args:
        analysis_response: The full AnalysisResponse from run_analysis().
        dataframes: Dict mapping ticker symbol → raw OHLCV+indicator DataFrame.

    Returns:
        PDF as raw bytes (ready for streaming HTTP response).
    """
    gen_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    page_callback = _make_page_callback(gen_time)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=0.75 * inch,
        title=f"Stock Pattern Engine Report — {gen_time}",
        author="Stock Pattern Engine v1.0.0",
        subject="Technical Analysis Report",
    )

    ST = _styles()
    elements: list = []

    # 1. Cover
    _build_cover(elements, analysis_response, ST, gen_time=gen_time)

    # 2. Executive Summary
    _build_executive_summary(elements, analysis_response, ST)

    # 3. Per-ticker sections
    for res in analysis_response.results:
        ticker = res.ticker
        df = dataframes.get(ticker, dataframes.get(ticker.upper(), pd.DataFrame()))
        if df.empty:
            elements.append(Paragraph(
                f"No raw data available for {ticker}.", ST["body"]
            ))
            elements.append(PageBreak())
            continue
        _build_ticker_section(elements, res, df.copy(), ST)

    # 4. Education page
    _build_education_page(elements, ST)

    doc.build(elements, onFirstPage=page_callback, onLaterPages=page_callback)
    buf.seek(0)
    return buf.read()


__all__ = ["generate_pdf_report"]
